### ISSUE TITLE
[Help Wanted] Container for Microsoft Edge & struggles with docker run

### ISSUE THREAD

**Issue by cyborghound** [fhoeben/hsac-fitnesse-docker#2]
Hi Fried,

I would like to make a container for Microsoft Edge, so that I have one container for everything.
I found the Selenium Edge standalone container but do not know where to start.
I don't know if this is very easy to do.

Also I have an issue with running the Chrome-container. When I run ./buildChrome.sh everything works fine till the docker container tries to run. Everytime the if statement is probably false because the container never starts.

When I remove the if statement, everything works well.

**Comment by fhoeben** [comment]
I thought you really didn't know where to start, but I see my comment below is not really needed anymore...

---

Did you find https://github.com/fhoeben/hsac-fitnesse-docker/blob/master/chrome/Dockerfile ?

You would need to build something similar. The basic steps are:

- mount 'hsac/test' image
- build new image from selenium standard image by:
  -  creating fitnesse directories
  - create link to WebDriver present in image to place where hsac-fixtures will expect it
  - ensure user from standard image is owner of the new directory
  - add script to start test run
  - disable standard image's config to launch selenium grid (we will run browser locally)
  - set environment for hsac-fixtures (you at least need to update browser there)
  - tell docker that the script we provided needs to be started when creating a container from this image
  - copy the compiled Java code and all dependencies into the image

**Comment by fhoeben** [comment]
Did you see where the `if` checks `TEST_IMAGES`? Do you have that environment variable set? If not try setting that to `true`, something like `EXPORT TEST_IMAGES=true`

Otherwise probably not all was fine because the return value from the build command was not `0`

**Comment by cyborghound** [comment]
Thank you Fried, I got it working by setting the parameter to true. I think something is also not working out when building. That's why there is no 0 as output. I'll check this later, because for now this part is working and I can run a test.

For the container I changed the following things to edge:

- I cloned the chrome folder and changed everything to edge. The official standalone edge container, the symlink to the msedgedriver enz.
- I made a clone of the buildChrome.sh and changed everything to edge, like the version, the images enz.
- I changed the browser to edge in the SuiteSetUp and kept the capabilities the same.

I ofcourse got some errors and found some information on the internet about what it could be. 

```
Oct 23, 2021 6:56:25 PM org.openqa.selenium.remote.DesiredCapabilities edge
INFO: Using `new EdgeOptions()` is preferred to `DesiredCapabilities.edge()`
Starting MSEdgeDriver 95.0.1020.20 (2e3504a099228f5ff15a34f581a73e3615cea8aa) on port 11073
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
[1635015385.207][SEVERE]: bind() failed: Cannot assign requested address (99)
Error shutting down selenium
nl.hsac.fitnesse.fixture.slim.StopTestException: session not created: No matching capabilities found
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'b039cdaf3c1b', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.47-linuxkit', java.version: '11.0.11'
Driver info: driver.version: EdgeDriver
```
The internet said it has something to do with IPv6, or the driver which can't find the edge installation on the base container. How does this work or did you see these errors before? Thanks :) I think i'm almost there.

**Comment by fhoeben** [comment]
I believe you are close indeed.

I have no experience with edge, but I recognise the 'address' error from chrome. There it can be safely ignored. I indeed believe it has something to do with IPv6, but was completely irrelevant for my needs.

So the problem remaining is that the edge driver is started but them seems unable to launch a session. The browser and capabilities,  in SuiteSetUp should be irrelevant as these should be overridden in properties on startup, i.e. the following lines in the `Dockerfile`
```
    -DseleniumBrowser=chrome \
    -DseleniumJsonProfile="{'args':['disable-dev-shm-usage']}"
```
I assume you switched the browser there to `edge`?
I don't know whether the `disable-dev-shm-usage` argument is supported by Edge. Have you tried removing that line?

Other than that the location of the edge executable might not be where the EdgeDriver expects it. Do you know where it lives in the selenium image you're using as base? Is there some configuration (e.g. environment variable) that you could/should do to make the driver aware of that location?

I see they have some form of wrapper setup in https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeEdge/wrap_edge_binary. It looks like `/usr/bin/microsoft-edge` is what should be run to launch Edge
